import type { TeamPalette } from './types'

export const MLB_TEAM_OVERRIDES: Readonly<Record<string, Partial<TeamPalette>>> = Object.freeze({
  'mlb:arizona-diamondbacks': {
    'base-bg': '#34141D',
    panel: '#4F1E2A',
    line: '#000000',
    accent: '#A71930',
    'accent-strong': '#E3D4AD',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(167, 25, 48, 0.34)',
    'bg-glow-b': 'rgba(0, 0, 0, 0.24)',
    headline: '"Black Ops One", "Anton", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Roboto Condensed", "Montserrat", "Segoe UI", sans-serif',
  },
  'mlb:atlanta-braves': {
    'base-bg': '#3F1221',
    panel: '#601B31',
    line: '#EAAA00',
    accent: '#CE1141',
    'accent-strong': '#13274F',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(206, 17, 65, 0.34)',
    'bg-glow-b': 'rgba(234, 170, 0, 0.24)',
    headline: '"Oswald", "Archivo Black", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Roboto Condensed", "Barlow Condensed", "Segoe UI", sans-serif',
  },
  'mlb:baltimore-orioles': {
    'base-bg': '#43210F',
    panel: '#673116',
    line: '#FFFFFF',
    accent: '#DF4601',
    'accent-strong': '#000000',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(223, 70, 1, 0.34)',
    'bg-glow-b': 'rgba(255, 255, 255, 0.24)',
    headline: '"Bangers", "Oswald", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Barlow Condensed", "Roboto Condensed", "Segoe UI", sans-serif',
  },
  'mlb:boston-red-sox': {
    'base-bg': '#3A1A1F',
    panel: '#59282E',
    line: '#FFFFFF',
    accent: '#BD3039',
    'accent-strong': '#0C2340',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(189, 48, 57, 0.34)',
    'bg-glow-b': 'rgba(255, 255, 255, 0.24)',
    headline: '"Alfa Slab One", "Graduate", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Roboto Slab", "Merriweather", "Segoe UI", serif',
  },
  'mlb:chicago-cubs': {
    'base-bg': '#091B35',
    panel: '#0F294E',
    line: '#FFFFFF',
    accent: '#0E3386',
    'accent-strong': '#CC3433',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(14, 51, 134, 0.34)',
    'bg-glow-b': 'rgba(255, 255, 255, 0.24)',
    headline: '"Bebas Neue", "Oswald", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Roboto Condensed", "Montserrat", "Segoe UI", sans-serif',
  },
  'mlb:chicago-white-sox': {
    'base-bg': '#101718',
    panel: '#1A2323',
    line: '#FFFFFF',
    accent: '#27251F',
    'accent-strong': '#C4CED4',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(39, 37, 31, 0.34)',
    'bg-glow-b': 'rgba(255, 255, 255, 0.24)',
    headline: '"Staatliches", "Black Ops One", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Roboto Condensed", "Exo 2", "Segoe UI", sans-serif',
  },
  'mlb:cincinnati-reds': {
    'base-bg': '#3C0D18',
    panel: '#5C1423',
    line: '#FFFFFF',
    accent: '#C6011F',
    'accent-strong': '#000000',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(198, 1, 31, 0.34)',
    'bg-glow-b': 'rgba(255, 255, 255, 0.24)',
    headline: '"Anton", "Bebas Neue", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Roboto Condensed", "Barlow Condensed", "Segoe UI", sans-serif',
  },
  'mlb:cleveland-guardians': {
    'base-bg': '#051D29',
    panel: '#092B3D',
    line: '#FFFFFF',
    accent: '#00385D',
    'accent-strong': '#E50022',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(0, 56, 93, 0.34)',
    'bg-glow-b': 'rgba(255, 255, 255, 0.24)',
    headline: '"Archivo Black", "Oswald", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Roboto Condensed", "Montserrat", "Segoe UI", sans-serif',
  },
  'mlb:colorado-rockies': {
    'base-bg': '#131B2C',
    panel: '#1F2941',
    line: '#131413',
    accent: '#333366',
    'accent-strong': '#C4CED4',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(51, 51, 102, 0.34)',
    'bg-glow-b': 'rgba(19, 20, 19, 0.24)',
    headline: '"Righteous", "Bebas Neue", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Exo 2", "Roboto Condensed", "Segoe UI", sans-serif',
  },
  'mlb:detroit-tigers': {
    'base-bg': '#081721',
    panel: '#0E2231',
    line: '#FFFFFF',
    accent: '#0C2340',
    'accent-strong': '#FA4616',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(12, 35, 64, 0.34)',
    'bg-glow-b': 'rgba(255, 255, 255, 0.24)',
    headline: '"Antonio", "Archivo Black", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Roboto Condensed", "Montserrat", "Segoe UI", sans-serif',
  },
  'mlb:houston-astros': {
    'base-bg': '#051A2B',
    panel: '#09273F',
    line: '#F4911E',
    accent: '#002D62',
    'accent-strong': '#EB6E1F',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(0, 45, 98, 0.34)',
    'bg-glow-b': 'rgba(244, 145, 30, 0.24)',
    headline: '"Orbitron", "Russo One", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Exo 2", "Roboto Condensed", "Segoe UI", sans-serif',
  },
  'mlb:kansas-city-royals': {
    'base-bg': '#052135',
    panel: '#09314F',
    line: '#FFFFFF',
    accent: '#004687',
    'accent-strong': '#BD9B60',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(0, 70, 135, 0.34)',
    'bg-glow-b': 'rgba(255, 255, 255, 0.24)',
    headline: '"Playfair Display", "Roboto Slab", "Space Grotesk", "Segoe UI", serif',
    body: '"Merriweather", "Montserrat", "Segoe UI", serif',
  },
  'mlb:los-angeles-angels': {
    'base-bg': '#3A0F1A',
    panel: '#5A1728',
    line: '#862633',
    accent: '#BA0021',
    'accent-strong': '#003263',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(186, 0, 33, 0.34)',
    'bg-glow-b': 'rgba(134, 38, 51, 0.24)',
    headline: '"Anton", "Alfa Slab One", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Roboto Condensed", "Montserrat", "Segoe UI", sans-serif',
  },
  'mlb:los-angeles-dodgers': {
    'base-bg': '#05263B',
    panel: '#093A58',
    line: '#A5ACAF',
    accent: '#005A9C',
    'accent-strong': '#EF3E42',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(0, 90, 156, 0.34)',
    'bg-glow-b': 'rgba(165, 172, 175, 0.24)',
    headline: '"Lobster", "Pacifico", "Space Grotesk", "Segoe UI", cursive',
    body: '"Montserrat", "Roboto Condensed", "Segoe UI", sans-serif',
  },
  'mlb:miami-marlins': {
    'base-bg': '#053B4E',
    panel: '#095874',
    line: '#41748D',
    accent: '#00A3E0',
    'accent-strong': '#EF3340',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(0, 163, 224, 0.34)',
    'bg-glow-b': 'rgba(65, 116, 141, 0.24)',
    headline: '"Knewave", "Bangers", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Exo 2", "Roboto Condensed", "Segoe UI", sans-serif',
  },
  'mlb:milwaukee-brewers': {
    'base-bg': '#0A1824',
    panel: '#112536',
    line: '#FFFFFF',
    accent: '#12284B',
    'accent-strong': '#FFC52F',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(18, 40, 75, 0.34)',
    'bg-glow-b': 'rgba(255, 255, 255, 0.24)',
    headline: '"Graduate", "Ultra", "Space Grotesk", "Segoe UI", serif',
    body: '"Roboto Slab", "Roboto Condensed", "Segoe UI", serif',
  },
  'mlb:minnesota-twins': {
    'base-bg': '#051929',
    panel: '#09263D',
    line: '#B9975B',
    accent: '#002B5C',
    'accent-strong': '#D31145',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(0, 43, 92, 0.34)',
    'bg-glow-b': 'rgba(185, 151, 91, 0.24)',
    headline: '"Oswald", "Archivo Black", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Roboto Condensed", "Barlow Condensed", "Segoe UI", sans-serif',
  },
  'mlb:new-york-mets': {
    'base-bg': '#051A2F',
    panel: '#092746',
    line: '#FFFFFF',
    accent: '#002D72',
    'accent-strong': '#FF5910',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(0, 45, 114, 0.34)',
    'bg-glow-b': 'rgba(255, 255, 255, 0.24)',
    headline: '"Bebas Neue", "Oswald", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Roboto Condensed", "Montserrat", "Segoe UI", sans-serif',
  },
  'mlb:new-york-yankees': {
    'base-bg': '#051A35',
    panel: '#09284F',
    line: '#0C2340',
    accent: '#003087',
    'accent-strong': '#E4002C',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(0, 48, 135, 0.34)',
    'bg-glow-b': 'rgba(12, 35, 64, 0.24)',
    headline: '"Playfair Display", "Graduate", "Space Grotesk", "Segoe UI", serif',
    body: '"Merriweather", "Roboto Slab", "Segoe UI", serif',
  },
  'mlb:oakland-athletics': {
    'base-bg': '#051D1D',
    panel: '#092B2B',
    line: '#A2AAAD',
    accent: '#003831',
    'accent-strong': '#EFB21E',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(0, 56, 49, 0.34)',
    'bg-glow-b': 'rgba(162, 170, 173, 0.24)',
    headline: '"Righteous", "Antonio", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Roboto Condensed", "Montserrat", "Segoe UI", sans-serif',
  },
  'mlb:philadelphia-phillies': {
    'base-bg': '#46141A',
    panel: '#6B1E27',
    line: '#FFFFFF',
    accent: '#E81828',
    'accent-strong': '#002D72',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(232, 24, 40, 0.34)',
    'bg-glow-b': 'rgba(255, 255, 255, 0.24)',
    headline: '"Anton", "Bebas Neue", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Roboto Condensed", "Barlow Condensed", "Segoe UI", sans-serif',
  },
  'mlb:pittsburgh-pirates': {
    'base-bg': '#101718',
    panel: '#1A2323',
    line: '#FFFFFF',
    accent: '#27251F',
    'accent-strong': '#FDB827',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(39, 37, 31, 0.34)',
    'bg-glow-b': 'rgba(255, 255, 255, 0.24)',
    headline: '"Ultra", "Black Ops One", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Roboto Slab", "Roboto Condensed", "Segoe UI", serif',
  },
  'mlb:san-diego-padres': {
    'base-bg': '#2F241D',
    panel: '#4A392D',
    line: '#FFFFFF',
    accent: '#5B4636',
    'accent-strong': '#FFC425',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(91, 70, 54, 0.34)',
    'bg-glow-b': 'rgba(255, 255, 255, 0.24)',
    headline: '"Staatliches", "Oswald", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Roboto Condensed", "Merriweather", "Segoe UI", sans-serif',
  },
  'mlb:san-francisco-giants': {
    'base-bg': '#4C2618',
    panel: '#743A23',
    line: '#EFD19F',
    accent: '#FD5A1E',
    'accent-strong': '#27251F',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(253, 90, 30, 0.34)',
    'bg-glow-b': 'rgba(239, 209, 159, 0.24)',
    headline: '"Bangers", "Anton", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Roboto Condensed", "Montserrat", "Segoe UI", sans-serif',
  },
  'mlb:mariners': {
    'base-bg': '#081927',
    panel: '#0E263A',
    line: '#C4CED4',
    accent: '#0C2C56',
    'accent-strong': '#005C5C',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(12, 44, 86, 0.34)',
    'bg-glow-b': 'rgba(196, 206, 212, 0.24)',
    headline: '"Orbitron", "Syncopate", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Exo 2", "Roboto Condensed", "Segoe UI", sans-serif',
  },
  'mlb:st-louis-cardinals': {
    'base-bg': '#3C151F',
    panel: '#5C202E',
    line: '#FEDB00',
    accent: '#C41E3A',
    'accent-strong': '#0C2340',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(196, 30, 58, 0.34)',
    'bg-glow-b': 'rgba(254, 219, 0, 0.24)',
    headline: '"Abril Fatface", "Alfa Slab One", "Space Grotesk", "Segoe UI", serif',
    body: '"Roboto Slab", "Merriweather", "Segoe UI", serif',
  },
  'mlb:tampa-bay-rays': {
    'base-bg': '#081929',
    panel: '#0D263D',
    line: '#F5D130',
    accent: '#092C5C',
    'accent-strong': '#8FBCE6',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(9, 44, 92, 0.34)',
    'bg-glow-b': 'rgba(245, 209, 48, 0.24)',
    headline: '"Archivo Black", "Montserrat", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Roboto Condensed", "Exo 2", "Segoe UI", sans-serif',
  },
  'mlb:texas-rangers': {
    'base-bg': '#051B31',
    panel: '#092948',
    line: '#FFFFFF',
    accent: '#003278',
    'accent-strong': '#C0111F',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(0, 50, 120, 0.34)',
    'bg-glow-b': 'rgba(255, 255, 255, 0.24)',
    headline: '"Russo One", "Oswald", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Roboto Condensed", "Barlow Condensed", "Segoe UI", sans-serif',
  },
  'mlb:toronto-blue-jays': {
    'base-bg': '#0A2237',
    panel: '#113352',
    line: '#E8291C',
    accent: '#134A8E',
    'accent-strong': '#1D2D5C',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(19, 74, 142, 0.34)',
    'bg-glow-b': 'rgba(232, 41, 28, 0.24)',
    headline: '"Syncopate", "Montserrat", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Roboto Condensed", "Exo 2", "Segoe UI", sans-serif',
  },
  'mlb:washington-nationals': {
    'base-bg': '#350D10',
    panel: '#511417',
    line: '#FFFFFF',
    accent: '#AB0003',
    'accent-strong': '#14225A',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(171, 0, 3, 0.34)',
    'bg-glow-b': 'rgba(255, 255, 255, 0.24)',
    headline: '"Roboto Slab", "Alfa Slab One", "Space Grotesk", "Segoe UI", serif',
    body: '"Merriweather", "Roboto Condensed", "Segoe UI", serif',
  },
})
