import type { TeamPalette } from './types'

export const NFL_TEAM_OVERRIDES: Readonly<Record<string, Partial<TeamPalette>>> = Object.freeze({
  'nfl:arizona-cardinals': {
    'base-bg': '#321221',
    panel: '#4F1E34',
    line: '#FFB612',
    accent: '#97233F',
    'accent-strong': '#000000',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(151, 35, 63, 0.34)',
    'bg-glow-b': 'rgba(255, 182, 18, 0.24)',
    headline: '"Black Ops One", "Bebas Neue", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Roboto Condensed", "Montserrat", "Segoe UI", sans-serif',
  },
  'nfl:atlanta-falcons': {
    'base-bg': '#370F1C',
    panel: '#561A2D',
    line: '#A5ACAF',
    accent: '#A71930',
    'accent-strong': '#000000',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(167, 25, 48, 0.34)',
    'bg-glow-b': 'rgba(165, 172, 175, 0.24)',
    headline: '"Oswald", "Kanit", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Barlow Condensed", "Roboto Condensed", "Segoe UI", sans-serif',
  },
  'nfl:baltimore-ravens': {
    'base-bg': '#100F31',
    panel: '#1A194C',
    line: '#9E7C0C',
    accent: '#241773',
    'accent-strong': '#000000',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(36, 23, 115, 0.34)',
    'bg-glow-b': 'rgba(158, 124, 12, 0.24)',
    headline: '"Russo One", "Orbitron", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Exo 2", "Kanit", "Segoe UI", sans-serif',
  },
  'nfl:buffalo-bills': {
    'base-bg': '#051738',
    panel: '#092658',
    line: '#7B1B53',
    accent: '#00338D',
    'accent-strong': '#C60C30',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(0, 51, 141, 0.34)',
    'bg-glow-b': 'rgba(198, 12, 48, 0.24)',
    headline: '"Archivo Black", "Montserrat", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Roboto Condensed", "Barlow Condensed", "Segoe UI", sans-serif',
  },
  'nfl:carolina-panthers': {
    'base-bg': '#0A0F18',
    panel: '#111925',
    line: '#BFC0BF',
    accent: '#0085CA',
    'accent-strong': '#101820',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(0, 133, 202, 0.34)',
    'bg-glow-b': 'rgba(191, 192, 191, 0.24)',
    headline: '"Orbitron", "Russo One", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Exo 2", "Roboto Condensed", "Segoe UI", sans-serif',
  },
  'nfl:chicago-bears': {
    'base-bg': '#080E1B',
    panel: '#0E182A',
    line: '#802B12',
    accent: '#0B162A',
    'accent-strong': '#C83803',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(11, 22, 42, 0.34)',
    'bg-glow-b': 'rgba(200, 56, 3, 0.24)',
    headline: '"Alfa Slab One", "Anton", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Roboto Condensed", "Montserrat", "Segoe UI", sans-serif',
  },
  'nfl:cincinnati-bengals': {
    'base-bg': '#501F14',
    panel: '#7D3220',
    line: '#5F1E08',
    accent: '#FB4F14',
    'accent-strong': '#000000',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(251, 79, 20, 0.34)',
    'bg-glow-b': 'rgba(0, 0, 0, 0.24)',
    headline: '"Bangers", "Anton", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Barlow Condensed", "Kanit", "Segoe UI", sans-serif',
  },
  'nfl:cleveland-browns': {
    'base-bg': '#14100E',
    panel: '#201B17',
    line: '#B13000',
    accent: '#311D00',
    'accent-strong': '#FF3C00',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(49, 29, 0, 0.34)',
    'bg-glow-b': 'rgba(255, 60, 0, 0.24)',
    headline: '"Ultra", "Graduate", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Roboto Condensed", "Montserrat", "Segoe UI", sans-serif',
  },
  'nfl:dallas-cowboys': {
    'base-bg': '#05183A',
    panel: '#09265B',
    line: '#7F9695',
    accent: '#003594',
    'accent-strong': '#869397',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(0, 53, 148, 0.34)',
    'bg-glow-b': 'rgba(127, 150, 149, 0.24)',
    headline: '"Montserrat", "Archivo Black", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Roboto Condensed", "Barlow Condensed", "Segoe UI", sans-serif',
  },
  'nfl:denver-broncos': {
    'base-bg': '#501F14',
    panel: '#7D3220',
    line: '#5F3332',
    accent: '#FB4F14',
    'accent-strong': '#002244',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(251, 79, 20, 0.34)',
    'bg-glow-b': 'rgba(0, 34, 68, 0.24)',
    headline: '"Bebas Neue", "Teko", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Barlow Condensed", "Roboto Condensed", "Segoe UI", sans-serif',
  },
  'nfl:detroit-lions': {
    'base-bg': '#052B45',
    panel: '#09446A',
    line: '#6D9EBA',
    accent: '#0076B6',
    'accent-strong': '#B0B7BC',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(0, 118, 182, 0.34)',
    'bg-glow-b': 'rgba(176, 183, 188, 0.24)',
    headline: '"Kanit", "Montserrat", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Roboto Condensed", "Exo 2", "Segoe UI", sans-serif',
  },
  'nfl:green-bay-packers': {
    'base-bg': '#0F181D',
    panel: '#18272D',
    line: '#AA861E',
    accent: '#203731',
    'accent-strong': '#FFB612',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(32, 55, 49, 0.34)',
    'bg-glow-b': 'rgba(255, 182, 18, 0.24)',
    headline: '"Graduate", "Alfa Slab One", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Roboto Condensed", "Montserrat", "Segoe UI", sans-serif',
  },
  'nfl:houston-texans': {
    'base-bg': '#06111C',
    panel: '#0B1D2C',
    line: '#691C30',
    accent: '#03202F',
    'accent-strong': '#A71930',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(3, 32, 47, 0.34)',
    'bg-glow-b': 'rgba(167, 25, 48, 0.24)',
    headline: '"Russo One", "Kanit", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Exo 2", "Roboto Condensed", "Segoe UI", sans-serif',
  },
  'nfl:indianapolis-colts': {
    'base-bg': '#05152B',
    panel: '#092242',
    line: '#9EAFC2',
    accent: '#002C5F',
    'accent-strong': '#A2AAAD',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(0, 44, 95, 0.34)',
    'bg-glow-b': 'rgba(162, 170, 173, 0.24)',
    headline: '"Archivo Black", "Montserrat", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Roboto Condensed", "Barlow Condensed", "Segoe UI", sans-serif',
  },
  'nfl:jacksonville-jaguars': {
    'base-bg': '#052732',
    panel: '#093D4E',
    line: '#9F792C',
    accent: '#006778',
    'accent-strong': '#D7A22A',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(0, 103, 120, 0.34)',
    'bg-glow-b': 'rgba(159, 121, 44, 0.24)',
    headline: '"Black Ops One", "Oswald", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Roboto Condensed", "Kanit", "Segoe UI", sans-serif',
  },
  'nfl:kansas-city-chiefs': {
    'base-bg': '#490F1F',
    panel: '#721930',
    line: '#F47B26',
    accent: '#E31837',
    'accent-strong': '#FFB81C',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(227, 24, 55, 0.34)',
    'bg-glow-b': 'rgba(255, 184, 28, 0.24)',
    headline: '"Anton", "Bebas Neue", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Roboto Condensed", "Barlow Condensed", "Segoe UI", sans-serif',
  },
  'nfl:las-vegas-raiders': {
    'base-bg': '#05080E',
    panel: '#090E17',
    line: '#666B6D',
    accent: '#000000',
    'accent-strong': '#A5ACAF',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(0, 0, 0, 0.34)',
    'bg-glow-b': 'rgba(165, 172, 175, 0.24)',
    headline: '"Black Ops One", "Staatliches", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Roboto Condensed", "Montserrat", "Segoe UI", sans-serif',
  },
  'nfl:los-angeles-chargers': {
    'base-bg': '#052E49',
    panel: '#094972',
    line: '#FFFFFF',
    accent: '#0080C6',
    'accent-strong': '#FFC20E',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(0, 128, 198, 0.34)',
    'bg-glow-b': 'rgba(255, 255, 255, 0.24)',
    headline: '"Orbitron", "Kanit", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Exo 2", "Roboto Condensed", "Segoe UI", sans-serif',
  },
  'nfl:los-angeles-rams': {
    'base-bg': '#05183A',
    panel: '#09265B',
    line: '#FF8200',
    accent: '#003594',
    'accent-strong': '#FFA300',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(0, 53, 148, 0.34)',
    'bg-glow-b': 'rgba(255, 130, 0, 0.24)',
    headline: '"Bangers", "Anton", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Barlow Condensed", "Roboto Condensed", "Segoe UI", sans-serif',
  },
  'nfl:miami-dolphins': {
    'base-bg': '#05323B',
    panel: '#094F5C',
    line: '#005778',
    accent: '#008E97',
    'accent-strong': '#FC4C02',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(0, 142, 151, 0.34)',
    'bg-glow-b': 'rgba(0, 87, 120, 0.24)',
    headline: '"Kanit", "Montserrat", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Exo 2", "Roboto Condensed", "Segoe UI", sans-serif',
  },
  'nfl:minnesota-vikings': {
    'base-bg': '#1D1335',
    panel: '#2E2053',
    line: '#BC894F',
    accent: '#4F2683',
    'accent-strong': '#FFC62F',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(79, 38, 131, 0.34)',
    'bg-glow-b': 'rgba(255, 198, 47, 0.24)',
    headline: '"Staatliches", "Russo One", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Roboto Condensed", "Barlow Condensed", "Segoe UI", sans-serif',
  },
  'nfl:new-england-patriots': {
    'base-bg': '#051222',
    panel: '#091E36',
    line: '#B0B7BC',
    accent: '#002244',
    'accent-strong': '#C60C30',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(0, 34, 68, 0.34)',
    'bg-glow-b': 'rgba(176, 183, 188, 0.24)',
    headline: '"Archivo Black", "Montserrat", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Roboto Condensed", "Barlow Condensed", "Segoe UI", sans-serif',
  },
  'nfl:new-orleans-saints': {
    'base-bg': '#0A0F18',
    panel: '#111925',
    line: '#897E64',
    accent: '#D3BC8D',
    'accent-strong': '#101820',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(211, 188, 141, 0.34)',
    'bg-glow-b': 'rgba(16, 24, 32, 0.24)',
    headline: '"Ultra", "Graduate", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Roboto Condensed", "Montserrat", "Segoe UI", sans-serif',
  },
  'nfl:new-york-giants': {
    'base-bg': '#08122C',
    panel: '#0E1E45',
    line: '#A5ACAF',
    accent: '#0B2265',
    'accent-strong': '#A71930',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(11, 34, 101, 0.34)',
    'bg-glow-b': 'rgba(165, 172, 175, 0.24)',
    headline: '"Oswald", "Archivo Black", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Roboto Condensed", "Exo 2", "Segoe UI", sans-serif',
  },
  'nfl:new-york-jets': {
    'base-bg': '#0A2221',
    panel: '#113634',
    line: '#FFFFFF',
    accent: '#125740',
    'accent-strong': '#000000',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(18, 87, 64, 0.34)',
    'bg-glow-b': 'rgba(255, 255, 255, 0.24)',
    headline: '"Teko", "Oswald", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Barlow Condensed", "Roboto Condensed", "Segoe UI", sans-serif',
  },
  'nfl:philadelphia-eagles': {
    'base-bg': '#051F27',
    panel: '#09313D',
    line: '#ACC0C6',
    accent: '#004C54',
    'accent-strong': '#A5ACAF',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(0, 76, 84, 0.34)',
    'bg-glow-b': 'rgba(172, 192, 198, 0.24)',
    headline: '"Black Ops One", "Kanit", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Roboto Condensed", "Exo 2", "Segoe UI", sans-serif',
  },
  'nfl:pittsburgh-steelers': {
    'base-bg': '#0A0F18',
    panel: '#111925',
    line: '#003087',
    accent: '#101820',
    'accent-strong': '#FFB612',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(16, 24, 32, 0.34)',
    'bg-glow-b': 'rgba(0, 48, 135, 0.24)',
    headline: '"Anton", "Archivo Black", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Roboto Condensed", "Montserrat", "Segoe UI", sans-serif',
  },
  'nfl:san-francisco-49ers': {
    'base-bg': '#38080E',
    panel: '#570E17',
    line: '#B05F3A',
    accent: '#AA0000',
    'accent-strong': '#B3995D',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(170, 0, 0, 0.34)',
    'bg-glow-b': 'rgba(179, 153, 93, 0.24)',
    headline: '"Bebas Neue", "Anton", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Roboto Condensed", "Montserrat", "Segoe UI", sans-serif',
  },
  'nfl:seahawks': {
    'base-bg': '#051222',
    panel: '#091E36',
    line: '#A5ACAF',
    accent: '#002244',
    'accent-strong': '#69BE28',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(0, 34, 68, 0.34)',
    'bg-glow-b': 'rgba(165, 172, 175, 0.24)',
    headline: '"Orbitron", "Russo One", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Exo 2", "Roboto Condensed", "Segoe UI", sans-serif',
  },
  'nfl:tampa-bay-buccaneers': {
    'base-bg': '#450B11',
    panel: '#6B131B',
    line: '#34302B',
    accent: '#D50A0A',
    'accent-strong': '#FF7900',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(213, 10, 10, 0.34)',
    'bg-glow-b': 'rgba(52, 48, 43, 0.24)',
    headline: '"Bangers", "Black Ops One", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Barlow Condensed", "Roboto Condensed", "Segoe UI", sans-serif',
  },
  'nfl:tennessee-titans': {
    'base-bg': '#091221',
    panel: '#0F1E34',
    line: '#C8102E',
    accent: '#0C2340',
    'accent-strong': '#4B92DB',
    'brand-color': '#FFFFFF',
    'bg-glow-a': 'rgba(12, 35, 64, 0.34)',
    'bg-glow-b': 'rgba(200, 16, 46, 0.24)',
    headline: '"Russo One", "Orbitron", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Exo 2", "Roboto Condensed", "Segoe UI", sans-serif',
  },
  'nfl:washington-commanders': {
    'base-bg': '#1A0B0D',
    panel: '#2A1114',
    line: '#5A1C24',
    accent: '#5A1414',
    'accent-strong': '#FFB612',
    'on-accent': '#F4E9E5',
    'on-accent-strong': '#2A1114',
    'brand-color': '#FFE4C4',
    'brand-surface': 'rgba(42, 17, 20, 0.80)',
    'brand-surface-border': 'rgba(255, 228, 196, 0.45)',
    link: '#FFE0A3',
    'link-hover': '#FFF1CE',
    'bg-glow-a': 'rgba(90, 20, 20, 0.45)',
    'bg-glow-b': 'rgba(255, 182, 18, 0.24)',
    headline: '"Alfa Slab One", "Anton", "Space Grotesk", "Segoe UI", sans-serif',
    body: '"Saira Condensed", "Roboto Condensed", "Segoe UI", sans-serif',
  },
})
