gemfile: Gemfile

# Hooks run locally in the rbenv environment
# After editing this file, re-sign: bundle exec overcommit --sign

PreCommit:
  RuboCop:
    enabled: true
    on_warn: fail
    command:
      - bundle
      - exec
      - rubocop

  ErbLint:
    enabled: true
    description: "Lint ERB templates"
    command:
      - bundle
      - exec
      - erb_lint
    flags: ["--lint-all"]
    run_on_applicable_files: false

  Brakeman:
    enabled: false
    command:
      - bundle
      - exec
      - brakeman
    flags: ["--quiet", "--no-pager", "--force"]
    run_on_applicable_files: false

  RSpec:
    enabled: true
    description: "Run unit and integration tests"
    command:
      - bundle
      - exec
      - rspec
    flags: ["spec/unit", "spec/integration"]
    run_on_applicable_files: false
