const NFL_TEAM_SLUGS = [
  'arizona-cardinals',
  'atlanta-falcons',
  'baltimore-ravens',
  'buffalo-bills',
  'carolina-panthers',
  'chicago-bears',
  'cincinnati-bengals',
  'cleveland-browns',
  'dallas-cowboys',
  'denver-broncos',
  'detroit-lions',
  'green-bay-packers',
  'houston-texans',
  'indianapolis-colts',
  'jacksonville-jaguars',
  'kansas-city-chiefs',
  'las-vegas-raiders',
  'los-angeles-chargers',
  'los-angeles-rams',
  'miami-dolphins',
  'minnesota-vikings',
  'new-england-patriots',
  'new-orleans-saints',
  'new-york-giants',
  'new-york-jets',
  'philadelphia-eagles',
  'pittsburgh-steelers',
  'san-francisco-49ers',
  'seahawks',
  'tampa-bay-buccaneers',
  'tennessee-titans',
  'washington-commanders',
] as const

const MLB_TEAM_SLUGS = [
  'arizona-diamondbacks',
  'atlanta-braves',
  'baltimore-orioles',
  'boston-red-sox',
  'chicago-cubs',
  'chicago-white-sox',
  'cincinnati-reds',
  'cleveland-guardians',
  'colorado-rockies',
  'detroit-tigers',
  'houston-astros',
  'kansas-city-royals',
  'los-angeles-angels',
  'los-angeles-dodgers',
  'miami-marlins',
  'milwaukee-brewers',
  'minnesota-twins',
  'new-york-mets',
  'new-york-yankees',
  'oakland-athletics',
  'philadelphia-phillies',
  'pittsburgh-pirates',
  'san-diego-padres',
  'san-francisco-giants',
  'mariners',
  'st-louis-cardinals',
  'tampa-bay-rays',
  'texas-rangers',
  'toronto-blue-jays',
  'washington-nationals',
] as const

const MLS_TEAM_SLUGS = [
  'atlanta-united',
  'austin-fc',
  'charlotte-fc',
  'chicago-fire',
  'fc-cincinnati',
  'colorado-rapids',
  'columbus-crew',
  'dc-united',
  'fc-dallas',
  'houston-dynamo',
  'inter-miami',
  'la-galaxy',
  'los-angeles-fc',
  'minnesota-united',
  'cf-montreal',
  'nashville-sc',
  'new-england-revolution',
  'new-york-city-fc',
  'new-york-red-bulls',
  'orlando-city',
  'philadelphia-union',
  'portland-timbers',
  'real-salt-lake',
  'san-diego-fc',
  'san-jose-earthquakes',
  'sounders',
  'sporting-kansas-city',
  'st-louis-city-sc',
  'toronto-fc',
  'vancouver-whitecaps-fc',
] as const

const NHL_TEAM_SLUGS = [
  'anaheim-ducks',
  'boston-bruins',
  'buffalo-sabres',
  'calgary-flames',
  'carolina-hurricanes',
  'chicago-blackhawks',
  'colorado-avalanche',
  'columbus-blue-jackets',
  'dallas-stars',
  'detroit-red-wings',
  'edmonton-oilers',
  'florida-panthers',
  'los-angeles-kings',
  'minnesota-wild',
  'montreal-canadiens',
  'nashville-predators',
  'new-jersey-devils',
  'new-york-islanders',
  'new-york-rangers',
  'ottawa-senators',
  'philadelphia-flyers',
  'pittsburgh-penguins',
  'san-jose-sharks',
  'kraken',
  'st-louis-blues',
  'tampa-bay-lightning',
  'toronto-maple-leafs',
  'utah-mammoth',
  'utah-hockey-club',
  'vancouver-canucks',
  'vegas-golden-knights',
  'washington-capitals',
  'winnipeg-jets',
] as const

const NBA_TEAM_SLUGS = [
  'atlanta-hawks',
  'boston-celtics',
  'brooklyn-nets',
  'charlotte-hornets',
  'chicago-bulls',
  'cleveland-cavaliers',
  'dallas-mavericks',
  'denver-nuggets',
  'detroit-pistons',
  'golden-state-warriors',
  'houston-rockets',
  'indiana-pacers',
  'la-clippers',
  'los-angeles-lakers',
  'memphis-grizzlies',
  'miami-heat',
  'milwaukee-bucks',
  'minnesota-timberwolves',
  'new-orleans-pelicans',
  'new-york-knicks',
  'oklahoma-city-thunder',
  'orlando-magic',
  'philadelphia-76ers',
  'phoenix-suns',
  'portland-trail-blazers',
  'sacramento-kings',
  'san-antonio-spurs',
  'supersonics',
  'toronto-raptors',
  'utah-jazz',
  'washington-wizards',
] as const

export const VALID_TEAM_KEYS = new Set<string>([
  ...NFL_TEAM_SLUGS.map((slug) => `nfl:${slug}`),
  ...MLB_TEAM_SLUGS.map((slug) => `mlb:${slug}`),
  ...MLS_TEAM_SLUGS.map((slug) => `mls:${slug}`),
  ...NHL_TEAM_SLUGS.map((slug) => `nhl:${slug}`),
  ...NBA_TEAM_SLUGS.map((slug) => `nba:${slug}`),
])
