export const LEAGUES = ['NFL', 'MLB', 'MLS', 'NHL', 'NBA'] as const

export type League = (typeof LEAGUES)[number]

export interface TeamOption {
  league: League
  key: string
  label: string
}

const NFL_TEAMS: readonly TeamOption[] = [
  { league: 'NFL', key: 'nfl:arizona-cardinals', label: 'Arizona Cardinals' },
  { league: 'NFL', key: 'nfl:atlanta-falcons', label: 'Atlanta Falcons' },
  { league: 'NFL', key: 'nfl:baltimore-ravens', label: 'Baltimore Ravens' },
  { league: 'NFL', key: 'nfl:buffalo-bills', label: 'Buffalo Bills' },
  { league: 'NFL', key: 'nfl:carolina-panthers', label: 'Carolina Panthers' },
  { league: 'NFL', key: 'nfl:chicago-bears', label: 'Chicago Bears' },
  { league: 'NFL', key: 'nfl:cincinnati-bengals', label: 'Cincinnati Bengals' },
  { league: 'NFL', key: 'nfl:cleveland-browns', label: 'Cleveland Browns' },
  { league: 'NFL', key: 'nfl:dallas-cowboys', label: 'Dallas Cowboys' },
  { league: 'NFL', key: 'nfl:denver-broncos', label: 'Denver Broncos' },
  { league: 'NFL', key: 'nfl:detroit-lions', label: 'Detroit Lions' },
  { league: 'NFL', key: 'nfl:green-bay-packers', label: 'Green Bay Packers' },
  { league: 'NFL', key: 'nfl:houston-texans', label: 'Houston Texans' },
  { league: 'NFL', key: 'nfl:indianapolis-colts', label: 'Indianapolis Colts' },
  { league: 'NFL', key: 'nfl:jacksonville-jaguars', label: 'Jacksonville Jaguars' },
  { league: 'NFL', key: 'nfl:kansas-city-chiefs', label: 'Kansas City Chiefs' },
  { league: 'NFL', key: 'nfl:las-vegas-raiders', label: 'Las Vegas Raiders' },
  { league: 'NFL', key: 'nfl:los-angeles-chargers', label: 'Los Angeles Chargers' },
  { league: 'NFL', key: 'nfl:los-angeles-rams', label: 'Los Angeles Rams' },
  { league: 'NFL', key: 'nfl:miami-dolphins', label: 'Miami Dolphins' },
  { league: 'NFL', key: 'nfl:minnesota-vikings', label: 'Minnesota Vikings' },
  { league: 'NFL', key: 'nfl:new-england-patriots', label: 'New England Patriots' },
  { league: 'NFL', key: 'nfl:new-orleans-saints', label: 'New Orleans Saints' },
  { league: 'NFL', key: 'nfl:new-york-giants', label: 'New York Giants' },
  { league: 'NFL', key: 'nfl:new-york-jets', label: 'New York Jets' },
  { league: 'NFL', key: 'nfl:philadelphia-eagles', label: 'Philadelphia Eagles' },
  { league: 'NFL', key: 'nfl:pittsburgh-steelers', label: 'Pittsburgh Steelers' },
  { league: 'NFL', key: 'nfl:san-francisco-49ers', label: 'San Francisco 49ers' },
  { league: 'NFL', key: 'nfl:seahawks', label: 'Seattle Seahawks' },
  { league: 'NFL', key: 'nfl:tampa-bay-buccaneers', label: 'Tampa Bay Buccaneers' },
  { league: 'NFL', key: 'nfl:tennessee-titans', label: 'Tennessee Titans' },
  { league: 'NFL', key: 'nfl:washington-commanders', label: 'Washington Commanders' },
]

const MLB_TEAMS: readonly TeamOption[] = [
  { league: 'MLB', key: 'mlb:arizona-diamondbacks', label: 'Arizona Diamondbacks' },
  { league: 'MLB', key: 'mlb:atlanta-braves', label: 'Atlanta Braves' },
  { league: 'MLB', key: 'mlb:baltimore-orioles', label: 'Baltimore Orioles' },
  { league: 'MLB', key: 'mlb:boston-red-sox', label: 'Boston Red Sox' },
  { league: 'MLB', key: 'mlb:chicago-cubs', label: 'Chicago Cubs' },
  { league: 'MLB', key: 'mlb:chicago-white-sox', label: 'Chicago White Sox' },
  { league: 'MLB', key: 'mlb:cincinnati-reds', label: 'Cincinnati Reds' },
  { league: 'MLB', key: 'mlb:cleveland-guardians', label: 'Cleveland Guardians' },
  { league: 'MLB', key: 'mlb:colorado-rockies', label: 'Colorado Rockies' },
  { league: 'MLB', key: 'mlb:detroit-tigers', label: 'Detroit Tigers' },
  { league: 'MLB', key: 'mlb:houston-astros', label: 'Houston Astros' },
  { league: 'MLB', key: 'mlb:kansas-city-royals', label: 'Kansas City Royals' },
  { league: 'MLB', key: 'mlb:los-angeles-angels', label: 'Los Angeles Angels' },
  { league: 'MLB', key: 'mlb:los-angeles-dodgers', label: 'Los Angeles Dodgers' },
  { league: 'MLB', key: 'mlb:miami-marlins', label: 'Miami Marlins' },
  { league: 'MLB', key: 'mlb:milwaukee-brewers', label: 'Milwaukee Brewers' },
  { league: 'MLB', key: 'mlb:minnesota-twins', label: 'Minnesota Twins' },
  { league: 'MLB', key: 'mlb:new-york-mets', label: 'New York Mets' },
  { league: 'MLB', key: 'mlb:new-york-yankees', label: 'New York Yankees' },
  { league: 'MLB', key: 'mlb:oakland-athletics', label: 'Athletics' },
  { league: 'MLB', key: 'mlb:philadelphia-phillies', label: 'Philadelphia Phillies' },
  { league: 'MLB', key: 'mlb:pittsburgh-pirates', label: 'Pittsburgh Pirates' },
  { league: 'MLB', key: 'mlb:san-diego-padres', label: 'San Diego Padres' },
  { league: 'MLB', key: 'mlb:san-francisco-giants', label: 'San Francisco Giants' },
  { league: 'MLB', key: 'mlb:mariners', label: 'Seattle Mariners' },
  { league: 'MLB', key: 'mlb:st-louis-cardinals', label: 'St. Louis Cardinals' },
  { league: 'MLB', key: 'mlb:tampa-bay-rays', label: 'Tampa Bay Rays' },
  { league: 'MLB', key: 'mlb:texas-rangers', label: 'Texas Rangers' },
  { league: 'MLB', key: 'mlb:toronto-blue-jays', label: 'Toronto Blue Jays' },
  { league: 'MLB', key: 'mlb:washington-nationals', label: 'Washington Nationals' },
]

const MLS_TEAMS: readonly TeamOption[] = [
  { league: 'MLS', key: 'mls:atlanta-united', label: 'Atlanta United FC' },
  { league: 'MLS', key: 'mls:austin-fc', label: 'Austin FC' },
  { league: 'MLS', key: 'mls:charlotte-fc', label: 'Charlotte FC' },
  { league: 'MLS', key: 'mls:chicago-fire', label: 'Chicago Fire FC' },
  { league: 'MLS', key: 'mls:fc-cincinnati', label: 'FC Cincinnati' },
  { league: 'MLS', key: 'mls:colorado-rapids', label: 'Colorado Rapids' },
  { league: 'MLS', key: 'mls:columbus-crew', label: 'Columbus Crew' },
  { league: 'MLS', key: 'mls:dc-united', label: 'D.C. United' },
  { league: 'MLS', key: 'mls:fc-dallas', label: 'FC Dallas' },
  { league: 'MLS', key: 'mls:houston-dynamo', label: 'Houston Dynamo FC' },
  { league: 'MLS', key: 'mls:inter-miami', label: 'Inter Miami CF' },
  { league: 'MLS', key: 'mls:la-galaxy', label: 'LA Galaxy' },
  { league: 'MLS', key: 'mls:los-angeles-fc', label: 'Los Angeles FC' },
  { league: 'MLS', key: 'mls:minnesota-united', label: 'Minnesota United FC' },
  { league: 'MLS', key: 'mls:cf-montreal', label: 'CF Montreal' },
  { league: 'MLS', key: 'mls:nashville-sc', label: 'Nashville SC' },
  { league: 'MLS', key: 'mls:new-england-revolution', label: 'New England Revolution' },
  { league: 'MLS', key: 'mls:new-york-city-fc', label: 'New York City FC' },
  { league: 'MLS', key: 'mls:new-york-red-bulls', label: 'New York Red Bulls' },
  { league: 'MLS', key: 'mls:orlando-city', label: 'Orlando City SC' },
  { league: 'MLS', key: 'mls:philadelphia-union', label: 'Philadelphia Union' },
  { league: 'MLS', key: 'mls:portland-timbers', label: 'Portland Timbers' },
  { league: 'MLS', key: 'mls:real-salt-lake', label: 'Real Salt Lake' },
  { league: 'MLS', key: 'mls:san-diego-fc', label: 'San Diego FC' },
  { league: 'MLS', key: 'mls:san-jose-earthquakes', label: 'San Jose Earthquakes' },
  { league: 'MLS', key: 'mls:sounders', label: 'Seattle Sounders FC' },
  { league: 'MLS', key: 'mls:sporting-kansas-city', label: 'Sporting Kansas City' },
  { league: 'MLS', key: 'mls:st-louis-city-sc', label: 'St. Louis City SC' },
  { league: 'MLS', key: 'mls:toronto-fc', label: 'Toronto FC' },
  { league: 'MLS', key: 'mls:vancouver-whitecaps-fc', label: 'Vancouver Whitecaps FC' },
]

const NHL_TEAMS: readonly TeamOption[] = [
  { league: 'NHL', key: 'nhl:anaheim-ducks', label: 'Anaheim Ducks' },
  { league: 'NHL', key: 'nhl:boston-bruins', label: 'Boston Bruins' },
  { league: 'NHL', key: 'nhl:buffalo-sabres', label: 'Buffalo Sabres' },
  { league: 'NHL', key: 'nhl:calgary-flames', label: 'Calgary Flames' },
  { league: 'NHL', key: 'nhl:carolina-hurricanes', label: 'Carolina Hurricanes' },
  { league: 'NHL', key: 'nhl:chicago-blackhawks', label: 'Chicago Blackhawks' },
  { league: 'NHL', key: 'nhl:colorado-avalanche', label: 'Colorado Avalanche' },
  { league: 'NHL', key: 'nhl:columbus-blue-jackets', label: 'Columbus Blue Jackets' },
  { league: 'NHL', key: 'nhl:dallas-stars', label: 'Dallas Stars' },
  { league: 'NHL', key: 'nhl:detroit-red-wings', label: 'Detroit Red Wings' },
  { league: 'NHL', key: 'nhl:edmonton-oilers', label: 'Edmonton Oilers' },
  { league: 'NHL', key: 'nhl:florida-panthers', label: 'Florida Panthers' },
  { league: 'NHL', key: 'nhl:los-angeles-kings', label: 'Los Angeles Kings' },
  { league: 'NHL', key: 'nhl:minnesota-wild', label: 'Minnesota Wild' },
  { league: 'NHL', key: 'nhl:montreal-canadiens', label: 'Montreal Canadiens' },
  { league: 'NHL', key: 'nhl:nashville-predators', label: 'Nashville Predators' },
  { league: 'NHL', key: 'nhl:new-jersey-devils', label: 'New Jersey Devils' },
  { league: 'NHL', key: 'nhl:new-york-islanders', label: 'New York Islanders' },
  { league: 'NHL', key: 'nhl:new-york-rangers', label: 'New York Rangers' },
  { league: 'NHL', key: 'nhl:ottawa-senators', label: 'Ottawa Senators' },
  { league: 'NHL', key: 'nhl:philadelphia-flyers', label: 'Philadelphia Flyers' },
  { league: 'NHL', key: 'nhl:pittsburgh-penguins', label: 'Pittsburgh Penguins' },
  { league: 'NHL', key: 'nhl:san-jose-sharks', label: 'San Jose Sharks' },
  { league: 'NHL', key: 'nhl:kraken', label: 'Seattle Kraken' },
  { league: 'NHL', key: 'nhl:st-louis-blues', label: 'St. Louis Blues' },
  { league: 'NHL', key: 'nhl:tampa-bay-lightning', label: 'Tampa Bay Lightning' },
  { league: 'NHL', key: 'nhl:toronto-maple-leafs', label: 'Toronto Maple Leafs' },
  { league: 'NHL', key: 'nhl:utah-hockey-club', label: 'Utah Mammoth' },
  { league: 'NHL', key: 'nhl:vancouver-canucks', label: 'Vancouver Canucks' },
  { league: 'NHL', key: 'nhl:vegas-golden-knights', label: 'Vegas Golden Knights' },
  { league: 'NHL', key: 'nhl:washington-capitals', label: 'Washington Capitals' },
  { league: 'NHL', key: 'nhl:winnipeg-jets', label: 'Winnipeg Jets' },
]

const NBA_TEAMS: readonly TeamOption[] = [
  { league: 'NBA', key: 'nba:atlanta-hawks', label: 'Atlanta Hawks' },
  { league: 'NBA', key: 'nba:boston-celtics', label: 'Boston Celtics' },
  { league: 'NBA', key: 'nba:brooklyn-nets', label: 'Brooklyn Nets' },
  { league: 'NBA', key: 'nba:charlotte-hornets', label: 'Charlotte Hornets' },
  { league: 'NBA', key: 'nba:chicago-bulls', label: 'Chicago Bulls' },
  { league: 'NBA', key: 'nba:cleveland-cavaliers', label: 'Cleveland Cavaliers' },
  { league: 'NBA', key: 'nba:dallas-mavericks', label: 'Dallas Mavericks' },
  { league: 'NBA', key: 'nba:denver-nuggets', label: 'Denver Nuggets' },
  { league: 'NBA', key: 'nba:detroit-pistons', label: 'Detroit Pistons' },
  { league: 'NBA', key: 'nba:golden-state-warriors', label: 'Golden State Warriors' },
  { league: 'NBA', key: 'nba:houston-rockets', label: 'Houston Rockets' },
  { league: 'NBA', key: 'nba:indiana-pacers', label: 'Indiana Pacers' },
  { league: 'NBA', key: 'nba:la-clippers', label: 'LA Clippers' },
  { league: 'NBA', key: 'nba:los-angeles-lakers', label: 'Los Angeles Lakers' },
  { league: 'NBA', key: 'nba:memphis-grizzlies', label: 'Memphis Grizzlies' },
  { league: 'NBA', key: 'nba:miami-heat', label: 'Miami Heat' },
  { league: 'NBA', key: 'nba:milwaukee-bucks', label: 'Milwaukee Bucks' },
  { league: 'NBA', key: 'nba:minnesota-timberwolves', label: 'Minnesota Timberwolves' },
  { league: 'NBA', key: 'nba:new-orleans-pelicans', label: 'New Orleans Pelicans' },
  { league: 'NBA', key: 'nba:new-york-knicks', label: 'New York Knicks' },
  { league: 'NBA', key: 'nba:oklahoma-city-thunder', label: 'Oklahoma City Thunder' },
  { league: 'NBA', key: 'nba:orlando-magic', label: 'Orlando Magic' },
  { league: 'NBA', key: 'nba:philadelphia-76ers', label: 'Philadelphia 76ers' },
  { league: 'NBA', key: 'nba:phoenix-suns', label: 'Phoenix Suns' },
  { league: 'NBA', key: 'nba:portland-trail-blazers', label: 'Portland Trail Blazers' },
  { league: 'NBA', key: 'nba:sacramento-kings', label: 'Sacramento Kings' },
  { league: 'NBA', key: 'nba:san-antonio-spurs', label: 'San Antonio Spurs' },
  { league: 'NBA', key: 'nba:supersonics', label: 'Seattle SuperSonics' },
  { league: 'NBA', key: 'nba:toronto-raptors', label: 'Toronto Raptors' },
  { league: 'NBA', key: 'nba:utah-jazz', label: 'Utah Jazz' },
  { league: 'NBA', key: 'nba:washington-wizards', label: 'Washington Wizards' },
]

export const TEAM_OPTIONS: readonly TeamOption[] = [
  ...NFL_TEAMS,
  ...MLB_TEAMS,
  ...MLS_TEAMS,
  ...NHL_TEAMS,
  ...NBA_TEAMS,
]

export const TEAM_KEYS = TEAM_OPTIONS.map((team) => team.key)
